---
abstract: 'Add SOURCE pod section for a github repository'
author:
  - 'Michael Schout <mschout@cpan.org>'
build_requires:
  Test::More: '0'
  perl: '5.006'
  strict: '0'
  warnings: '0'
configure_requires:
  ExtUtils::MakeMaker: '0'
  perl: '5.004'
dynamic_config: 0
generated_by: 'Dist::Zilla version 6.009, CPAN::Meta::Converter version 2.150005'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Pod-Weaver-Section-SourceGitHub
requires:
  Moose: '0'
  Moose::Autobox: '0'
  Pod::Weaver::Role::Section: '0'
  perl: '5.006'
resources:
  bugtracker: http://rt.cpan.org/Public/Dist/Display.html?Name=Pod-Weaver-Section-SourceGitHub
  homepage: http://search.cpan.org/dist/Pod-Weaver-Section-SourceGitHub/
  repository: git://github.com/mschout/pod-weaver-section-sourcegithub.git
version: '0.56'
x_serialization_backend: 'YAML::Tiny version 1.69'
